### ISSUE TITLE
Add favicons

### ISSUE THREAD

**Issue by Shelton** [operable/cog-book#20]

**Comment by Shelton** [comment]
Follow this: https://github.com/asciidoctor/asciidoctor/issues/1574

**Comment by Shelton** [comment]
PR https://github.com/operable/cog-book/pull/56 attempts to add a favicon + other meta data. I was able to get meta data listed in the published HTML, but the favicon still doesnt' show. Will check out over the break.

**Comment by splashx** [comment]
The favicon [is present](https://realfavicongenerator.net/favicon_checker?protocol=http&site=book.cog.bot#.WzFMFS2B3BJ) in desktop browsers. Closing this - in case mobile is also a requirement a new issue should be opened.
