### ISSUE TITLE
Need differentiation between a command and view snippet

### ISSUE THREAD

**Issue by Shelton** [operable/cog-book#24]
![screenshot 2016-11-04 09 48 00](https://cloud.githubusercontent.com/assets/1584889/20007757/237732d4-a274-11e6-95c5-6f16a4692049.png)

**Comment by splashx** [comment]
I propose using `console` for logs. It would look like this:

<img width="731" alt="screen shot 2018-06-25 at 22 28 09" src="https://user-images.githubusercontent.com/1154133/41874086-2801bb82-78c7-11e8-8a18-23476834b5e8.png">

**Comment by splashx** [comment]
I would recommend using `:: code-block: console`. It would look like this (third block):

<img width="727" alt="screen shot 2018-06-25 at 23 15 30" src="https://user-images.githubusercontent.com/1154133/41876340-c14ff5be-78cd-11e8-8c41-b31aa89ed6fa.png">
